"""Client Timeline model for tracking all client interactions and events."""

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import DateTime, Enum, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.clients.models import Client
    from app.users.models import User


class TimelineEventType(str, enum.Enum):
    """Enum for timeline event types."""
    
    # Client lifecycle
    CLIENT_CREATED = "CLIENT_CREATED"
    CLIENT_UPDATED = "CLIENT_UPDATED"
    STATUS_CHANGED = "STATUS_CHANGED"
    AGENT_ASSIGNED = "AGENT_ASSIGNED"
    
    # Attendances
    ATTENDANCE_STARTED = "ATTENDANCE_STARTED"
    ATTENDANCE_COMPLETED = "ATTENDANCE_COMPLETED"
    
    # Visits
    VISIT_SCHEDULED = "VISIT_SCHEDULED"
    VISIT_CONFIRMED = "VISIT_CONFIRMED"
    VISIT_COMPLETED = "VISIT_COMPLETED"
    VISIT_CANCELLED = "VISIT_CANCELLED"
    VISIT_NO_SHOW = "VISIT_NO_SHOW"
    
    # AI Insights
    AI_INSIGHT_GENERATED = "AI_INSIGHT_GENERATED"
    AI_SUGGESTION_APPLIED = "AI_SUGGESTION_APPLIED"
    AI_PROPERTY_RECOMMENDED = "AI_PROPERTY_RECOMMENDED"
    
    # Property Selection
    PROPERTY_SELECTED = "PROPERTY_SELECTED"
    PROPERTY_CONFIRMED = "PROPERTY_CONFIRMED"
    
    # Negotiation
    PROPOSAL_SENT = "PROPOSAL_SENT"
    PROPOSAL_ACCEPTED = "PROPOSAL_ACCEPTED"
    PROPOSAL_REJECTED = "PROPOSAL_REJECTED"
    PRICE_NEGOTIATION = "PRICE_NEGOTIATION"
    
    # Sales
    SALE_COMPLETED = "SALE_COMPLETED"
    CONTRACT_SIGNED = "CONTRACT_SIGNED"
    SALE_CANCELLED = "SALE_CANCELLED"
    
    # AI Updates
    CLIENT_UPDATED_BY_AI = "CLIENT_UPDATED_BY_AI"
    
    
    # General
    NOTE_ADDED = "NOTE_ADDED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    CONTACT_ATTEMPT = "CONTACT_ATTEMPT"


class ClientTimeline(Base):
    """
    Client Timeline model for tracking all interactions and events.
    
    This creates a complete history of the client journey, enabling:
    - Full audit trail of all interactions
    - AI context for better analysis
    - Visual timeline for users
    - Pattern detection across events
    
    Attributes:
        id: Unique identifier (UUID)
        client_id: Foreign key to Client
        event_type: Type of event
        title: Short title for the event
        description: Detailed description
        metadata: JSON metadata with event-specific data
        related_attendance_id: Related attendance (if applicable)
        related_visit_id: Related visit (if applicable)
        related_property_id: Related property (if applicable)
        created_by_id: User who triggered the event (if applicable)
        ai_generated: Whether this event was generated by AI
        importance: Importance level (1-5, 5 being most important)
        created_at: Timestamp when event occurred
    """
    
    __tablename__ = "client_timeline"
    
    # Primary key
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )
    
    # Required fields
    client_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("clients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    event_type: Mapped[TimelineEventType] = mapped_column(
        Enum(TimelineEventType, native_enum=False, length=30),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )
    
    # Extra data for event-specific information
    event_data: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Event-specific data (e.g., old/new values, AI scores, etc.)",
    )
    
    # Related entities
    related_attendance_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("attendances.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    related_visit_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("visits.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    related_property_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("properties.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    
    # User who triggered the event
    created_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    
    # AI and importance
    ai_generated: Mapped[bool] = mapped_column(
        default=False,
        nullable=False,
    )
    importance: Mapped[int] = mapped_column(
        default=3,
        nullable=False,
        comment="Importance level 1-5 (5 = most important)",
    )
    
    # Timestamp
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        nullable=False,
        index=True,
    )
    
    # Relationships
    client: Mapped["Client"] = relationship(
        "Client",
        foreign_keys=[client_id],
        lazy="selectin",
    )
    created_by: Mapped["User | None"] = relationship(
        "User",
        foreign_keys=[created_by_id],
        lazy="selectin",
    )
    
    def __repr__(self) -> str:
        """String representation."""
        return f"<ClientTimeline(id={self.id}, client_id={self.client_id}, event={self.event_type})>"

