"""create attendances table

Revision ID: 8b2285420a18
Revises: f9ebeeff18f2
Create Date: 2026-02-03 23:10:04.585076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2285420a18'
down_revision: Union[str, None] = 'f9ebeeff18f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('WHATSAPP', 'SITE', 'PHONE', 'EMAIL', 'IN_PERSON', name='attendancechannel', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True, comment='Duration in seconds, calculated automatically when ended_at is set'),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_next_steps', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'PAUSED', name='attendancestatus', native_enum=False, length=20), nullable=False),
    sa.Column('updated_client_status', sa.Text(), nullable=True, comment='JSON string with client status updates: current_status, current_interest_type, current_property_type'),
    sa.Column('scheduled_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_agent_id'), 'attendances', ['agent_id'], unique=False)
    op.create_index(op.f('ix_attendances_channel'), 'attendances', ['channel'], unique=False)
    op.create_index(op.f('ix_attendances_client_id'), 'attendances', ['client_id'], unique=False)
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_index(op.f('ix_attendances_property_id'), 'attendances', ['property_id'], unique=False)
    op.create_index(op.f('ix_attendances_scheduled_visit_at'), 'attendances', ['scheduled_visit_at'], unique=False)
    op.create_index(op.f('ix_attendances_started_at'), 'attendances', ['started_at'], unique=False)
    op.create_index(op.f('ix_attendances_status'), 'attendances', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendances_status'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_started_at'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_scheduled_visit_at'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_property_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_client_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_channel'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_agent_id'), table_name='attendances')
    op.drop_table('attendances')
    # ### end Alembic commands ###

