"""create_ai_summaries_table

Revision ID: d10f16e5ec7a
Revises: 925b1a1d5180
Create Date: 2026-02-05 23:18:59.310559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10f16e5ec7a'
down_revision: Union[str, None] = '925b1a1d5180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create ENUM types
    op.execute("CREATE TYPE aisummarystatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REPROCESSING')")
    op.execute("CREATE TYPE sentiment AS ENUM ('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'MIXED')")
    op.execute("CREATE TYPE detectedintent AS ENUM ('INFORMATION_REQUEST', 'PROPERTY_SEARCH', 'SCHEDULE_VISIT', 'PRICE_NEGOTIATION', 'DOCUMENTATION_REQUEST', 'GENERAL_INQUIRY', 'COMPLAINT', 'FOLLOW_UP')")
    
    # Create ai_summaries table
    op.create_table('ai_summaries',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('attendance_id', sa.UUID(), nullable=False),
        sa.Column('client_id', sa.UUID(), nullable=False),
        sa.Column('summary_text', sa.Text(), nullable=False, comment='Main summary text generated by AI'),
        sa.Column('key_points', sa.dialects.postgresql.JSONB(), nullable=True, comment='JSON array of key points extracted from attendance'),
        sa.Column('detected_intent', sa.Enum('INFORMATION_REQUEST', 'PROPERTY_SEARCH', 'SCHEDULE_VISIT', 'PRICE_NEGOTIATION', 'DOCUMENTATION_REQUEST', 'GENERAL_INQUIRY', 'COMPLAINT', 'FOLLOW_UP', name='detectedintent', native_enum=False, length=30), nullable=True),
        sa.Column('interest_type_detected', sa.String(length=20), nullable=True, comment='Detected interest type: BUY, RENT, SELL, INVEST'),
        sa.Column('budget_min_detected', sa.Float(), nullable=True, comment='Minimum budget detected in attendance'),
        sa.Column('budget_max_detected', sa.Float(), nullable=True, comment='Maximum budget detected in attendance'),
        sa.Column('urgency_level_detected', sa.String(length=20), nullable=True, comment='Detected urgency level: LOW, MEDIUM, HIGH, IMMEDIATE'),
        sa.Column('lead_score_suggested', sa.Integer(), nullable=True, comment='AI-suggested lead score (0-100)'),
        sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'MIXED', name='sentiment', native_enum=False, length=20), nullable=True),
        sa.Column('model_used', sa.String(length=100), nullable=True, comment="AI model identifier used for generation (e.g., 'gpt-4', 'claude-3')"),
        sa.Column('prompt_version', sa.String(length=50), nullable=True, comment='Version of the prompt template used'),
        sa.Column('confidence_score', sa.Float(), nullable=True, comment='Confidence score of the AI analysis (0.0-1.0)'),
        sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REPROCESSING', name='aisummarystatus', native_enum=False, length=20), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if processing failed'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('attendance_id', name='uq_ai_summaries_attendance_id')
    )
    
    # Create indexes
    op.create_index(op.f('ix_ai_summaries_id'), 'ai_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_attendance_id'), 'ai_summaries', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_client_id'), 'ai_summaries', ['client_id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_detected_intent'), 'ai_summaries', ['detected_intent'], unique=False)
    op.create_index(op.f('ix_ai_summaries_interest_type_detected'), 'ai_summaries', ['interest_type_detected'], unique=False)
    op.create_index(op.f('ix_ai_summaries_urgency_level_detected'), 'ai_summaries', ['urgency_level_detected'], unique=False)
    op.create_index(op.f('ix_ai_summaries_sentiment'), 'ai_summaries', ['sentiment'], unique=False)
    op.create_index(op.f('ix_ai_summaries_status'), 'ai_summaries', ['status'], unique=False)
    op.create_index(op.f('ix_ai_summaries_created_at'), 'ai_summaries', ['created_at'], unique=False)


def downgrade() -> None:
    # Drop indexes
    op.drop_index(op.f('ix_ai_summaries_created_at'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_status'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_sentiment'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_urgency_level_detected'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_interest_type_detected'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_detected_intent'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_client_id'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_attendance_id'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_id'), table_name='ai_summaries')
    
    # Drop table
    op.drop_table('ai_summaries')
    
    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS detectedintent")
    op.execute("DROP TYPE IF EXISTS sentiment")
    op.execute("DROP TYPE IF EXISTS aisummarystatus")

