"""AI Summary model for AI-generated summaries from attendances."""

import enum
import json
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Enum, ForeignKey, Float, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.attendances.models import Attendance
    from app.clients.models import Client


class AISummaryStatus(str, enum.Enum):
    """Enum for AI summary processing status."""

    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REPROCESSING = "REPROCESSING"


class Sentiment(str, enum.Enum):
    """Enum for detected sentiment."""

    POSITIVE = "POSITIVE"
    NEUTRAL = "NEUTRAL"
    NEGATIVE = "NEGATIVE"
    MIXED = "MIXED"


class DetectedIntent(str, enum.Enum):
    """Enum for detected intent from attendance."""

    INFORMATION_REQUEST = "INFORMATION_REQUEST"
    PROPERTY_SEARCH = "PROPERTY_SEARCH"
    SCHEDULE_VISIT = "SCHEDULE_VISIT"
    PRICE_NEGOTIATION = "PRICE_NEGOTIATION"
    DOCUMENTATION_REQUEST = "DOCUMENTATION_REQUEST"
    GENERAL_INQUIRY = "GENERAL_INQUIRY"
    COMPLAINT = "COMPLAINT"
    FOLLOW_UP = "FOLLOW_UP"


class AISummary(Base):
    """
    AI Summary model for storing AI-generated summaries from attendances.

    This model stores structured AI analysis of attendances, including:
    - Summary text and key points
    - Detected intent, interest type, budget, urgency
    - Suggested lead score
    - Sentiment analysis
    - Model metadata and confidence scores

    Attributes:
        id: Unique identifier (UUID)
        attendance_id: Foreign key to Attendance (unique - one summary per attendance)
        client_id: Foreign key to Client
        summary_text: Main summary text generated by AI
        key_points: JSON array of key points extracted
        detected_intent: Detected intent from the attendance
        interest_type_detected: Detected interest type (BUY, RENT, SELL, INVEST)
        budget_min_detected: Minimum budget detected (nullable)
        budget_max_detected: Maximum budget detected (nullable)
        urgency_level_detected: Detected urgency level (LOW, MEDIUM, HIGH, IMMEDIATE)
        lead_score_suggested: AI-suggested lead score (0-100)
        sentiment: Detected sentiment (POSITIVE, NEUTRAL, NEGATIVE, MIXED)
        model_used: AI model identifier used for generation
        prompt_version: Version of the prompt template used
        confidence_score: Confidence score of the AI analysis (0.0-1.0)
        status: Processing status (PENDING, PROCESSING, COMPLETED, FAILED, REPROCESSING)
        error_message: Error message if processing failed (nullable)
        created_at: Timestamp when summary was created
        
        # Relationships
        attendance: Relationship to Attendance
        client: Relationship to Client
    """

    __tablename__ = "ai_summaries"

    # Primary key
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )

    # Relationships
    attendance_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("attendances.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
        comment="One AI summary per attendance (unique constraint)",
    )
    client_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("clients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Summary content
    summary_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Main summary text generated by AI",
    )
    key_points: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="JSON array of key points extracted from attendance",
    )
    recommended_properties: Mapped[list[uuid.UUID] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Array of recommended property IDs based on client preferences extracted from attendance",
    )

    # Detected information
    detected_intent: Mapped[DetectedIntent | None] = mapped_column(
        Enum(DetectedIntent, native_enum=False, length=30),
        nullable=True,
        index=True,
    )
    interest_type_detected: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        index=True,
        comment="Detected interest type: BUY, RENT, SELL, INVEST",
    )
    budget_min_detected: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Minimum budget detected in attendance",
    )
    budget_max_detected: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Maximum budget detected in attendance",
    )
    urgency_level_detected: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        index=True,
        comment="Detected urgency level: LOW, MEDIUM, HIGH, IMMEDIATE",
    )
    lead_score_suggested: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        comment="AI-suggested lead score (0-100)",
    )
    sentiment: Mapped[Sentiment | None] = mapped_column(
        Enum(Sentiment, native_enum=False, length=20),
        nullable=True,
        index=True,
    )

    # AI model metadata
    model_used: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        comment="AI model identifier used for generation (e.g., 'gpt-4', 'claude-3')",
    )
    prompt_version: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        comment="Version of the prompt template used",
    )
    confidence_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Confidence score of the AI analysis (0.0-1.0)",
    )

    # Processing status
    status: Mapped[AISummaryStatus] = mapped_column(
        Enum(AISummaryStatus, native_enum=False, length=20),
        default=AISummaryStatus.PENDING,
        nullable=False,
        index=True,
    )
    error_message: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Error message if processing failed",
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        nullable=False,
        index=True,
    )

    # Relationships
    attendance: Mapped["Attendance"] = relationship(
        "Attendance",
        foreign_keys=[attendance_id],
        lazy="selectin",
    )
    client: Mapped["Client"] = relationship(
        "Client",
        foreign_keys=[client_id],
        lazy="selectin",
    )

    # Unique constraint: one summary per attendance
    __table_args__ = (
        UniqueConstraint("attendance_id", name="uq_ai_summaries_attendance_id"),
    )

    def __repr__(self) -> str:
        """String representation of the AISummary."""
        return f"<AISummary(id={self.id}, attendance_id={self.attendance_id}, status={self.status})>"


