"""Pydantic schemas for AI Summary validation and serialization."""

import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from app.ai.models import AISummaryStatus, DetectedIntent, Sentiment
from app.clients.models import InterestType, UrgencyLevel


class AISummaryBase(BaseModel):
    """Base schema for AI summary data."""

    attendance_id: uuid.UUID = Field(..., description="Attendance ID (unique - one summary per attendance)")
    client_id: uuid.UUID = Field(..., description="Client ID")
    summary_text: str = Field(..., min_length=1, description="Main summary text generated by AI")
    key_points: dict | None = Field(None, description="JSON object/array of key points extracted")
    detected_intent: DetectedIntent | None = Field(None, description="Detected intent from attendance")
    interest_type_detected: InterestType | None = Field(None, description="Detected interest type")
    budget_min_detected: float | None = Field(None, ge=0, description="Minimum budget detected")
    budget_max_detected: float | None = Field(None, ge=0, description="Maximum budget detected")
    urgency_level_detected: UrgencyLevel | None = Field(None, description="Detected urgency level")
    lead_score_suggested: int | None = Field(None, ge=0, le=100, description="AI-suggested lead score (0-100)")
    sentiment: Sentiment | None = Field(None, description="Detected sentiment")
    model_used: str | None = Field(None, max_length=100, description="AI model identifier used")
    prompt_version: str | None = Field(None, max_length=50, description="Version of the prompt template used")
    confidence_score: float | None = Field(None, ge=0.0, le=1.0, description="Confidence score (0.0-1.0)")
    recommended_properties: list[uuid.UUID] | None = Field(
        None,
        description="Array of recommended property IDs based on client preferences",
    )
    status: AISummaryStatus = Field(
        AISummaryStatus.PENDING,
        description="Processing status (defaults to PENDING)",
    )
    error_message: str | None = Field(None, description="Error message if processing failed")


class AISummaryCreate(AISummaryBase):
    """
    Schema for creating a new AI summary.

    Usually created automatically by the AI service when processing an attendance.
    """

    pass


class AISummaryUpdate(BaseModel):
    """
    Schema for updating AI summary information.

    All fields are optional to allow partial updates.
    Useful for reprocessing or updating status.
    """

    summary_text: str | None = Field(None, min_length=1)
    key_points: dict | None = None
    detected_intent: DetectedIntent | None = None
    interest_type_detected: InterestType | None = None
    budget_min_detected: float | None = Field(None, ge=0)
    budget_max_detected: float | None = Field(None, ge=0)
    urgency_level_detected: UrgencyLevel | None = None
    lead_score_suggested: int | None = Field(None, ge=0, le=100)
    sentiment: Sentiment | None = None
    model_used: str | None = Field(None, max_length=100)
    prompt_version: str | None = Field(None, max_length=50)
    confidence_score: float | None = Field(None, ge=0.0, le=1.0)
    recommended_properties: list[uuid.UUID] | None = None
    status: AISummaryStatus | None = None
    error_message: str | None = None


class AISummaryResponse(AISummaryBase):
    """
    Schema for AI summary response.

    Includes all base fields plus id and created_at timestamp.
    """

    id: uuid.UUID
    created_at: datetime

    class Config:
        """Pydantic config."""

        from_attributes = True


# Chat schemas
class ChatContext(BaseModel):
    """Context data for chat requests."""

    client_id: uuid.UUID | None = Field(None, description="Optional client ID for context")
    property_id: uuid.UUID | None = Field(None, description="Optional property ID for context")
    attendance_id: uuid.UUID | None = Field(None, description="Optional attendance ID for context")


class ChatRequest(BaseModel):
    """Request schema for AI chat endpoint."""

    message: str = Field(..., min_length=1, max_length=2000, description="User's question or message")
    context: ChatContext | None = Field(None, description="Optional context IDs to load data from database")


class ChatResponse(BaseModel):
    """Response schema for AI chat endpoint."""

    answer: str = Field(..., description="AI's response to the user's question")
    error: str | None = Field(None, description="Error message if request failed")


