"""Pydantic schemas for AI Summary validation and serialization."""

import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from app.ai.models import AISummaryStatus, DetectedIntent, Sentiment
from app.clients.models import InterestType, UrgencyLevel


class AISummaryBase(BaseModel):
    """Base schema for AI summary data."""

    attendance_id: uuid.UUID = Field(..., description="Attendance ID (unique - one summary per attendance)")
    client_id: uuid.UUID = Field(..., description="Client ID")
    summary_text: str = Field(..., min_length=1, description="Main summary text generated by AI")
    key_points: dict | None = Field(None, description="JSON object/array of key points extracted")
    detected_intent: DetectedIntent | None = Field(None, description="Detected intent from attendance")
    interest_type_detected: InterestType | None = Field(None, description="Detected interest type")
    budget_min_detected: float | None = Field(None, ge=0, description="Minimum budget detected")
    budget_max_detected: float | None = Field(None, ge=0, description="Maximum budget detected")
    urgency_level_detected: UrgencyLevel | None = Field(None, description="Detected urgency level")
    lead_score_suggested: int | None = Field(None, ge=0, le=100, description="AI-suggested lead score (0-100)")
    sentiment: Sentiment | None = Field(None, description="Detected sentiment")
    model_used: str | None = Field(None, max_length=100, description="AI model identifier used")
    prompt_version: str | None = Field(None, max_length=50, description="Version of the prompt template used")
    confidence_score: float | None = Field(None, ge=0.0, le=1.0, description="Confidence score (0.0-1.0)")
    recommended_properties: list[uuid.UUID] | None = Field(
        None,
        description="Array of recommended property IDs based on client preferences",
    )
    status: AISummaryStatus = Field(
        AISummaryStatus.PENDING,
        description="Processing status (defaults to PENDING)",
    )
    error_message: str | None = Field(None, description="Error message if processing failed")


class AISummaryCreate(AISummaryBase):
    """
    Schema for creating a new AI summary.

    Usually created automatically by the AI service when processing an attendance.
    """

    pass


class AISummaryUpdate(BaseModel):
    """
    Schema for updating AI summary. All fields optional (reprocessamento ou correção manual).
    """

    summary_text: str | None = Field(None, min_length=1, description="Texto principal do resumo")
    key_points: dict | None = Field(None, description="Pontos-chave (JSON)")
    detected_intent: DetectedIntent | None = Field(None, description="Intenção detectada")
    interest_type_detected: InterestType | None = Field(None, description="Tipo de interesse detectado")
    budget_min_detected: float | None = Field(None, ge=0, description="Orçamento mínimo detectado")
    budget_max_detected: float | None = Field(None, ge=0, description="Orçamento máximo detectado")
    urgency_level_detected: UrgencyLevel | None = Field(None, description="Nível de urgência detectado")
    lead_score_suggested: int | None = Field(None, ge=0, le=100, description="Lead score sugerido (0–100)")
    sentiment: Sentiment | None = Field(None, description="Sentimento detectado")
    model_used: str | None = Field(None, max_length=100, description="Modelo de IA utilizado")
    prompt_version: str | None = Field(None, max_length=50, description="Versão do prompt")
    confidence_score: float | None = Field(None, ge=0.0, le=1.0, description="Confiança (0–1)")
    recommended_properties: list[uuid.UUID] | None = Field(None, description="IDs de imóveis recomendados")
    status: AISummaryStatus | None = Field(None, description="PENDING, PROCESSING, COMPLETED, FAILED, REPROCESSING")
    error_message: str | None = Field(None, description="Mensagem de erro se falhou")


class AISummaryResponse(AISummaryBase):
    """
    Schema for AI summary response. Inclui todos os campos base, id e created_at.
    """

    id: uuid.UUID = Field(..., description="UUID do resumo")
    created_at: datetime = Field(..., description="Data de criação")

    class Config:
        """Pydantic config."""

        from_attributes = True


# Chat schemas
class ChatContext(BaseModel):
    """IDs opcionais para carregar dados do CRM no contexto do chat."""

    client_id: uuid.UUID | None = Field(None, description="ID do cliente para contexto")
    property_id: uuid.UUID | None = Field(None, description="ID do imóvel para contexto")
    attendance_id: uuid.UUID | None = Field(None, description="ID do atendimento para contexto")


class ChatRequest(BaseModel):
    """Request do chat com a IA."""

    message: str = Field(..., min_length=1, max_length=2000, description="Pergunta ou mensagem do usuário")
    context: ChatContext | None = Field(None, description="IDs opcionais (cliente, imóvel, atendimento) para carregar dados")
    include_dashboard: bool = Field(False, description="Incluir métricas da dashboard no contexto (ex.: gestor na página dashboard)")


class ChatResponse(BaseModel):
    """Resposta do chat com a IA."""

    answer: str = Field(..., description="Resposta da IA")
    error: str | None = Field(None, description="Mensagem de erro se a requisição falhou")


